### ISSUE TITLE
Request: add dataset as Git LFS

### ISSUE THREAD

**Issue by katnoria** [neulab/wikiasp#1]
Hello, I am trying to add your dataset into hugginface datasets library (https://github.com/huggingface/datasets). 
Currently, we are unable to download to files directly from releases because of the way GitHub manages (i.e stores) the assets.

Would it be possible for you to instead add the files as LFS (https://git-lfs.github.com/)?

```
git lfs track "*.bz2"
mkdir data
# copy bz2 files in the data directory
git add data
git commit 
```

I would have submitted the pull request but GitHub does not allow adding LFS to the forks 😯

**Comment by rooa** [comment]
Thanks for your interest in putting the dataset into huggingface datasets!
I'm uploading the LFS objects now but it will probably take some time because uploading speed is pretty slow. I'll ping here once they are pushed.

**Comment by rooa** [comment]
Hey @katnoria, it turned out that our large dataset doesn't fit into the Git LFS storage we have here, so we can't help with adding the data as LFS. Sorry about that. I am not familiar with adding a new dataset to HF/datasets, but is this a requirement for a dataset to be added?
Could you tell us a bit more about the following you mentioned? The download link seems to be working at least on my end.
> we are unable to download to files directly from releases because of the way GitHub manages (i.e stores) the assets

**Comment by katnoria** [comment]
Thanks @rooa , I too figured that there is a hard limit on free Git LFS storage. Thanks for looking into it.

Regarding the download link, I agree that it works from the browser and even on the terminal using `wget`. 
The downloader code in HF/datasets library does not support the URL redirection (i.e. if you use wget to fetch the dataset, you will notice that the requests are forwarded from GitHub URL to AWS URL). 

Since HF/datasets does not directly host the dataset, the only other way I can think of is to host it on AWS or Google Drive. If its not feasible, then I will close this request and come back again if I find any other way.

**Comment by rooa** [comment]
No worries! Thanks for the clarification. Then we will provide a different hosting solution that won't lead to redirection and let you know. I'll re-open the issue until they get uploaded.

**Comment by rooa** [comment]
Hi @katnoria, we now host the data in a different location as well. Please try using `http://phontron.com/download/wikiasp/<DOMAIN>.tar.bz2` and see if it works.

**Comment by katnoria** [comment]
Appreciate your help @rooa, let me try

**Comment by katnoria** [comment]
Thanks a lot @rooa, This solution works 😃.

**Comment by rooa** [comment]
Thanks @katnoria for your effort in putting the data to HF/datasets! I'll close the issue for now.
