### ISSUE TITLE
Mapping to Wikipedia article title 

### ISSUE THREAD

**Issue by fabrahman** [neulab/wikiasp#2]
Hello,
Thank you for open sourcing this dataset. 

1) I wonder if there is any meta data to map the data instances to Wiki title?

2) Also, when following the process of WikiSum did you only use the `Commoncrawl` part of the data and not the `web`? 

Thanks,

**Comment by rooa** [comment]
Hi! Thank you for your interest.

> 1: mapping instances to wikipedia titles (articles)

We can't provide the metadata right now, but will work on it and update here once they are compiled together.

> 2: commoncrawl or web

We used `CommonCrawl` part of the data only.

**Comment by fabrahman** [comment]
> Hi! Thank you for your interest.
> 
> > 1: mapping instances to wikipedia titles (articles)
> 
> We can't provide the metadata right now, but will work on it and update here once they are compiled together.
> 
> > 2: commoncrawl or web
> 
> We used `CommonCrawl` part of the data only.

Thanks for your reply. 
By metadata I meant just the article titles. Is there any other way I can get the article title for each instance in WikiAsp?

**Comment by rooa** [comment]
Sorry I missed your point before. I suppose the data in its current form doesn't have enough info to find the title for each instance. I have the original data with the titles but have no access for the next few days due to technical difficulty. I'll get back to that once that's resolved.

If it's urgent, you could follow WikiSum's data generation script to obtain raw instances and I could let you know specific instances we used for WikiAsp separately.

**Comment by fabrahman** [comment]
> Sorry I missed your point before. I suppose the data in its current form doesn't have enough info to find the title for each instance. I have the original data with the titles but have no access for the next few days due to technical difficulty. I'll get back to that once that's resolved.
> 
> If it's urgent, you could follow WikiSum's data generation script to obtain raw instances and I could let you know specific instances we used for WikiAsp separately.

That would be great if you could share files with the titles whenever you get a chance. Thanks.

**Comment by fabrahman** [comment]
Just to follow-up, do you have an estimate of when you can possibly release the titles? Thank you in advance.

**Comment by fabrahman** [comment]
Also, I was wondering if your original data has the information about document boundaries in the inputs? In the current version `inputs` are all tokenized at sentence level so the document boundaries are not preserved. Many thanks
